# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [31]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key

gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [11]:
city_data_path = "../output_data/cities1.csv"

city_data = pd.read_csv(city_data_path)

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [12]:
locations = city_data[["Lat", "Lng"]]
humidity = city_data["Humidity"].astype(float)

fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=2.5)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [39]:
city_data_1 = city_data.set_index("Unnamed: 0")


#Dataframe includes cities with "good weather", measured by low humidity (<80), no cloudiness, and moderate max temps (between 70 and 90 degrees)

city_data_nice = city_data_1.loc[(city_data_1["Humidity"] < 80) & (city_data_1["Cloudiness"] == 0) & (city_data_1["Max Temp"] < 90) & (city_data_1["Max Temp"] > 70)]


hotel_df = city_data_nice

hotel_df

#Create Column for Hotel Name
hotel_df["Hotel Name"] = ""
hotel_df.head()

<ipython-input-39-4b8d1ec41225>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_df["Hotel Name"] = ""

,City,Lat,Lng,Temp,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
Unnamed: 0,,,,,,,,,,,
21,busselton,-33.6500,115.3333,79.68,82.0,46,0,1.01,AU,1612228858,
68,broken hill,-31.9500,141.4333,71.60,71.6,30,0,18.41,AU,1612228869,
140,esperance,-33.8667,121.9000,71.60,71.6,53,0,14.97,AU,1612228625,
162,phetchabun,16.2500,101.0833,76.24,82.0,78,0,4.00,TH,1612228893,
182,vila velha,-20.3297,-40.2925,77.86,78.8,78,0,5.75,BR,1612228631,

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [42]:
params = {
    "radius": 5000,
    "types": "lodging",
    "keyword": "hotel",
    "key": g_key
}


#BH: Store Latitude and Longitude in locations
hotel_locations = hotel_df[["Lat", "Lng"]]

for index, row in hotel_df.iterrows():

    lat = row["Lat"]
    lng = row["Lng"]

    params["location"] = f"{lat},{lng}"


# base url
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    hotel_info = requests.get(base_url, params)

    hotel_info = hotel_info.json()
    
    try:
        hotel_df.loc[index, "Hotel Name"] = hotel_info["results"][0]["name"]
    except:
        print("Missing Hotel... Skipping")



#print(json.dumps(hotel_info, indent=4, sort_keys=True))


#hotel_df["Hotel Name"] = hotel_name
hotel_df

Missing Hotel... Skipping
Missing Hotel... Skipping
Missing Hotel... Skipping
Missing Hotel... Skipping
Missing Hotel... Skipping
Missing Hotel... Skipping

,City,Lat,Lng,Temp,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
Unnamed: 0,,,,,,,,,,,
21,busselton,-33.6500,115.3333,79.68,82.00,46,0,1.01,AU,1612228858,The Sebel Busselton
68,broken hill,-31.9500,141.4333,71.60,71.60,30,0,18.41,AU,1612228869,The Imperial Fine Accommodation
140,esperance,-33.8667,121.9000,71.60,71.60,53,0,14.97,AU,1612228625,The Jetty Resort
162,phetchabun,16.2500,101.0833,76.24,82.00,78,0,4.00,TH,1612228893,
182,vila velha,-20.3297,-40.2925,77.86,78.80,78,0,5.75,BR,1612228631,Hotel Senac Ilha do Boi
186,biltine,14.5333,20.9167,70.32,70.32,22,0,6.51,TD,1612228899,
232,perth,-31.9333,115.8333,86.00,86.00,28,0,12.66,AU,1612228650,Quay Perth
261,comodoro rivadavia,-45.8667,-67.5000,71.60,71.60,64,0,1.14,AR,1612228918,Lucania Palazzo Hotel
264,ahipara,-35.1667,173.1667,72.54,72.54,52,0,3.87,NZ,1612228919,The Huts
271,manzanillo,20.3433,-77.1167,74.95,74.95,72,0,9.71,CU,1612228920,Hostal Reliance (Casa Julio & Mayra)
273,tchollire,8.4022,14.1698,71.29,71.29,23,0,1.05,CM,1612228922,
293,kavaratti,10.5669,72.6420,81.18,81.18,75,0,9.28,IN,1612228927,yaad Hotal
318,bara,10.3744,10.7288,70.66,70.66,22,0,6.13,NG,1612228933,
336,sao filipe,14.8961,-24.4956,72.12,72.12,75,0,8.75,CV,1612228938,La Fora Ecolodge
404,trelew,-43.2490,-65.3051,75.65,75.65,25,0,23.82,AR,1612228958,Hotel Galicia
442,namuac,18.6109,121.1657,74.73,74.73,73,0,9.24,PH,1612228969,
472,yaan,7.3833,8.5667,79.12,79.12,72,0,11.01,NG,1612228976,
514,kawhia,-38.0651,174.8183,79.11,80.01,40,0,3.00,NZ,1612228987,Kawhia Motel
521,esmeraldas,-19.7625,-44.3139,74.59,75.20,64,0,4.61,BR,1612228989,Parque do Avestruz Hotel Fazenda

In [47]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [48]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
# Add the layer to the map
fig.add_layer(markers)
fig


# Display figure

Figure(layout=FigureLayout(height='420px'))